In [1]:
println("Hello World")

Hello World


In [2]:
x = 10

10

In [3]:
x + 1

11

In [4]:
pi

π = 3.1415926535897...

In [5]:
sqrt(4)

2.0

In [6]:
typeof(1)

Int64

In [7]:
Sys.WORD_SIZE

64

In [8]:
1.

1.0

In [9]:
.5

0.5

In [10]:
println(-1.23)
println(1e10)
println(2.5e-4)

-1.23
1.0e10
0.00025


In [11]:
10_000, 0.000_000_005, 0xdead_beef, 0b1011_0010

(10000, 5.0e-9, 0xdeadbeef, 0xb2)

In [12]:
0.0 == -0.0

true

In [13]:
bitstring(0.0)

"0000000000000000000000000000000000000000000000000000000000000000"

In [14]:
bitstring(-0.0)

"1000000000000000000000000000000000000000000000000000000000000000"

In [15]:
println(1 / Inf)
println(1 / 0)
println(-5 / 0)
println(0.000001/0)
println(0/0)
println(500 + Inf)
println(500 - Inf)
println(Inf + Inf)
println(Inf - Inf)
println(Inf * Inf)
println(Inf / Inf)
println(0 * Inf)

0.0
Inf
-Inf
Inf
NaN
Inf
-Inf
Inf
NaN
Inf
NaN
NaN


In [16]:
x = 3
println(2x^2 - 3x + 1)
println(1.5x^2 - .5x + 1)

10
13.0


In [19]:
println(~123)
println(123 & 234)
println(123 | 234)
println(123 ⊻ 234)
println(1 >>> 5)
println(1 >> 5)
println(1 << 5)

-124
106
251
145
0
0
32


In [20]:
x = 1
println(x += 3)
println(x)

4
4


In [21]:
[1, 2, 3] .^ 3

3-element Array{Int64,1}:
  1
  8
 27

In [22]:
1 < 2 <= 2 < 3 == 3 > 2 >= 1 == 1 < 3 != 5

true

In [23]:
v(x) = (println(x); x)

v (generic function with 1 method)

In [24]:
v(1) < v(2) <= v(3)

2
1
3


true

In [25]:
v(1) > v(2) <= v(3)

2
1


false

In [26]:
'x'

'x': ASCII/Unicode U+0078 (category Ll: Letter, lowercase)

In [27]:
typeof(ans)

Char

In [28]:
Int('x')

120

In [29]:
Char(120)

'x': ASCII/Unicode U+0078 (category Ll: Letter, lowercase)

In [30]:
'A' < 'a'

true

In [32]:
str = "Hello, world.\n"
println(str)

Hello, world.



In [33]:
"""Contains "quote" characters"""

"Contains \"quote\" characters"

In [38]:
str = "Hello"
println(str[begin])
println(str[end])

H
o


In [40]:
println(str[end-1])
println(str[end÷2])

l
e


In [41]:
s = "\u2200 x \u2203 y"

"∀ x ∃ y"

In [42]:
println(s[1])
println(s[2])
println(s[3])
println(s[4])

∀


StringIndexError: StringIndexError("∀ x ∃ y", 2)

In [43]:
println(s[end-1])
println(s[end-2])

StringIndexError: StringIndexError("∀ x ∃ y", 9)

In [44]:
s[prevind(s, end, 2)]

'∃': Unicode U+2203 (category Sm: Symbol, math)

In [45]:
for i = firstindex(s):lastindex(s)
    try
        println(s[i])
    catch
    end
end

∀
 
x
 
∃
 
y


In [46]:
for c in s
    println(c)
end

∀
 
x
 
∃
 
y


In [47]:
collect(eachindex(s))

7-element Array{Int64,1}:
  1
  4
  5
  6
  7
 10
 11

In [48]:
s = "\xc0\xa0\xe2\x88\xe2|"
foreach(display, s)

'\xc0\xa0': [overlong] ASCII/Unicode U+0020 (category Zs: Separator, space)

'\xe2\x88': Malformed UTF-8 (category Ma: Malformed, bad data)

'\xe2': Malformed UTF-8 (category Ma: Malformed, bad data)

'|': ASCII/Unicode U+007C (category Sm: Symbol, math)

In [50]:
isvalid.(collect(s))

4-element BitArray{1}:
 0
 0
 0
 1

In [51]:
greet = "Hello"
whom = "World"

string(greet, ", ", whom, ".\n")

"Hello, World.\n"

In [53]:
a, b = "\xe2\x88", "\x80"
c = a*b
println(c)

∀


In [54]:
collect.([a,b,c])

3-element Array{Array{Char,1},1}:
 ['\xe2\x88']
 ['\x80']
 ['∀']

In [55]:
length.([a,b,c])

3-element Array{Int64,1}:
 1
 1
 1

In [56]:
greet * ", " * whom * ".\n"

"Hello, World.\n"

In [57]:
"$greet, $whom.\n"

"Hello, World.\n"

In [58]:
"1 + 2 = $(1 + 2)"

"1 + 2 = 3"

In [67]:
v1 = [1,2,3]
v1

3-element Array{Int64,1}:
 1
 2
 3

In [68]:
"v: $v1"

"v: [1, 2, 3]"

In [69]:
c = 'x'
"hi, $c"

"hi, x"

In [70]:
print("I have \$100 in my account.\n")

I have $100 in my account.


In [71]:
str = """
           Hello,
           world.
         """

"  Hello,\n  world.\n"

In [72]:
"""    This
         is
           a test"""

"    This\nis\n  a test"