In [1]:
zeros(Int8, 2, 3)

2×3 Array{Int8,2}:
 0  0  0
 0  0  0

In [2]:
zeros(Int8, (2, 3))

2×3 Array{Int8,2}:
 0  0  0
 0  0  0

In [3]:
zeros((2, 3))

2×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0

## One - Dimensional Arrays

In [4]:
[1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

In [5]:
promote(1, 2.3, 4//5)

(1.0, 2.3, 0.8)

In [6]:
[1, 2.3, 4//5]

3-element Array{Float64,1}:
 1.0
 2.3
 0.8

In [7]:
[1:2, 4:5]

2-element Array{UnitRange{Int64},1}:
 1:2
 4:5

In [8]:
[1:2; 4:5]

4-element Array{Int64,1}:
 1
 2
 4
 5

In [11]:
[1:2
4:5
6]

5-element Array{Int64,1}:
 1
 2
 4
 5
 6

In [12]:
[1:2 4:5 7:8]

2×3 Array{Int64,2}:
 1  4  7
 2  5  8

In [13]:
[[1,2]  [4,5]  [7,8]]

2×3 Array{Int64,2}:
 1  4  7
 2  5  8

In [14]:
[1 2 3]

1×3 Array{Int64,2}:
 1  2  3

In [17]:
[1 2
3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [18]:
[zeros(Int, 2, 2) [1; 2]
        [3 4]       5]

3×3 Array{Int64,2}:
 0  0  1
 0  0  2
 3  4  5

In [19]:
[[1 2] [3 4]]

1×4 Array{Int64,2}:
 1  2  3  4

In [20]:
Int8[[1 2] [3 4]]

1×4 Array{Int8,2}:
 1  2  3  4

In [21]:
x = rand(8)

8-element Array{Float64,1}:
 0.40642049096883004
 0.6716781805363223
 0.7561259142573469
 0.12859294073056193
 0.6189886749155145
 0.6268797719518371
 0.6585814003279149
 0.43939426367610457

In [22]:
[0.25*x[i-1] + 0.5*x[i] + 0.25*x[i+1] for i=2:length(x)-1]

6-element Array{Float64,1}:
 0.6264756915747054
 0.5781307374453946
 0.4080751176584963
 0.498362515628357
 0.6328324047867759
 0.5958592090709429

In [23]:
Float32[0.25*x[i-1] + 0.5*x[i] + 0.25*x[i+1] for i=2:length(x)-1]

6-element Array{Float32,1}:
 0.6264757
 0.5781307
 0.40807512
 0.4983625
 0.6328324
 0.5958592

In [24]:
sum(1/n^2 for n=1:1000)

1.6439345666815615

In [25]:
map(tuple, 1/(i+j) for i=1:2, j=1:2, [1:4;])

LoadError: syntax: invalid iteration specification

In [26]:
map(tuple, (1/(i+j) for i=1:2, j=1:2), [1 3; 2 4])

2×2 Array{Tuple{Float64,Int64},2}:
 (0.5, 1)       (0.333333, 3)
 (0.333333, 2)  (0.25, 4)

In [27]:
[(i,j) for i=1:3 for j=1:i]

6-element Array{Tuple{Int64,Int64},1}:
 (1, 1)
 (2, 1)
 (2, 2)
 (3, 1)
 (3, 2)
 (3, 3)

In [28]:
[(i,j) for i=1:3 for j=1:i if i+j == 4]

2-element Array{Tuple{Int64,Int64},1}:
 (2, 2)
 (3, 1)

In [29]:
A = reshape(collect(1:16), (2, 2, 2, 2))

2×2×2×2 Array{Int64,4}:
[:, :, 1, 1] =
 1  3
 2  4

[:, :, 2, 1] =
 5  7
 6  8

[:, :, 1, 2] =
  9  11
 10  12

[:, :, 2, 2] =
 13  15
 14  16

In [30]:
A[1, 2, 1, 1]

3

In [31]:
A[[1, 2], [1], [1, 2], [1]]

2×1×2×1 Array{Int64,4}:
[:, :, 1, 1] =
 1
 2

[:, :, 2, 1] =
 5
 6

In [32]:
A[[1, 2], [1], [1, 2], 1]

2×1×2 Array{Int64,3}:
[:, :, 1] =
 1
 2

[:, :, 2] =
 5
 6

In [33]:
A[[1 2; 1 2]]

2×2 Array{Int64,2}:
 1  2
 1  2

In [34]:
A[[1 2; 1 2], 1, 2, 1]

2×2 Array{Int64,2}:
 5  6
 5  6

In [35]:
x = reshape(1:16, 4, 4)

4×4 reshape(::UnitRange{Int64}, 4, 4) with eltype Int64:
 1  5   9  13
 2  6  10  14
 3  7  11  15
 4  8  12  16

In [36]:
x[2:3, 2:end-1]

2×2 Array{Int64,2}:
 6  10
 7  11

In [37]:
x[1, [2 3; 4 1]]

2×2 Array{Int64,2}:
  5  9
 13  1

In [38]:
x = collect(reshape(1:9, 3, 3))

3×3 Array{Int64,2}:
 1  4  7
 2  5  8
 3  6  9

In [39]:
x[3, 3] = -9;

In [40]:
x[1:2, 1:2] = [-1 -4; -2 -5];

In [41]:
x

3×3 Array{Int64,2}:
 -1  -4   7
 -2  -5   8
  3   6  -9

In [42]:
A = reshape(collect(1:2:18), (3, 3))

3×3 Array{Int64,2}:
 1   7  13
 3   9  15
 5  11  17

In [43]:
println(A[4])
println(A[[2, 5, 8]])
println(A[[1 4; 3 8]])
println(A[1:2:5])
println(A[2, :])
println(A[:, 3])

7
[3, 9, 15]
[1 7; 5 15]
[1, 5, 9]
[3, 9, 15]
[13, 15, 17]


In [44]:
A = reshape(1:32, 4, 4, 2)
println(A[3, 2, 1])
println(A[CartesianIndex(3, 2, 1)] == A[3, 2, 1] == 7)

7
true


In [45]:
page = A[:,:,1]

4×4 Array{Int64,2}:
 1  5   9  13
 2  6  10  14
 3  7  11  15
 4  8  12  16

In [46]:
page[[CartesianIndex(1,1),
             CartesianIndex(2,2),
             CartesianIndex(3,3),
             CartesianIndex(4,4)]]

4-element Array{Int64,1}:
  1
  6
 11
 16

In [47]:
println(A[CartesianIndex.(axes(A, 1), axes(A, 2)), 1])
println(A[CartesianIndex.(axes(A, 1), axes(A, 2)), :])

[1, 6, 11, 16]
[1 17; 6 22; 11 27; 16 32]


In [49]:
x = reshape(1:16, 4, 4)
println(x[[false, true, true, false], :])
mask = map(ispow2, x)
println(mask)
println(x[mask])

[2 6 10 14; 3 7 11 15]
Bool[1 0 0 0; 1 0 0 0; 0 0 0 0; 1 1 0 1]
[1, 2, 4, 8, 16]


## Iterating an Array

In [50]:
A = rand(4, 3)

4×3 Array{Float64,2}:
 0.984546  0.831673   0.313429
 0.799104  0.794751   0.51333
 0.563952  0.108692   0.915284
 0.276359  0.0258619  0.805391

In [51]:
for a in A
    println(a)
end

0.9845458901334083
0.7991036913009006
0.5639520167435681
0.27635869781607125
0.831672544792593
0.7947513687419112
0.10869183415731798
0.025861894525691875
0.3134289575835796
0.5133303326972105
0.9152840966736184
0.8053914751938764


In [55]:
for a in eachindex(A)
    println(A[a])
end

0.9845458901334083
0.7991036913009006
0.5639520167435681
0.27635869781607125
0.831672544792593
0.7947513687419112
0.10869183415731798
0.025861894525691875
0.3134289575835796
0.5133303326972105
0.9152840966736184
0.8053914751938764


In [56]:
B = view(A, 1:3, 2:3)

3×2 view(::Array{Float64,2}, 1:3, 2:3) with eltype Float64:
 0.831673  0.313429
 0.794751  0.51333
 0.108692  0.915284

In [57]:
for i in eachindex(B)
    @show i
end

i = CartesianIndex(1, 1)
i = CartesianIndex(2, 1)
i = CartesianIndex(3, 1)
i = CartesianIndex(1, 2)
i = CartesianIndex(2, 2)
i = CartesianIndex(3, 2)
